name: build

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.5.1
      with:
          packages: |
            python3-minimal
            curl
            g++
            libgdk-pixbuf2.0-dev
            cmake
            libx11-dev
            libxmu-dev
            libglu1-mesa-dev
            libgl2ps-dev
            libxi-dev
            libzip-dev
            libpng-dev
            libcurl4-gnutls-dev
            libfontconfig1-dev
            libsqlite3-dev
            libglew-dev
            libssl-dev
            libgtk-3-dev
            libglfw3
            libglfw3-dev
            xorg-dev

    - name: Build
      run: |
        ./tools/cocos2d-console/bin/cocos compile -p linux -s tests/cpp-tests
